# Завдання 2
Розв’язати систему алгебраїчних рівнянь за допомогою [формул Крамера](https://uk.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0) і виконати перевірку за допомогою:
1. матричного множення;
2. оберненої матриці;
3. функції **numpy.linalg.solve()**.

Порівняти всі рішення за допомогою функції **numpy.allclose()**. 

$$
\begin{cases}
x_{2} -3x_{3} + 4x_{4} = -5 \\
x_{1} -2x_{3} + 3x_{4} = -4 \\
3x_{1} + 2x_{2} -5x_{4} = 12 \\
4x_{1} + 3x_{2} -5x_{3} = 5 \\
\end{cases}\,
$$

[LaTeX online](https://latexeditor.lagrida.com/)<br>
[Multiline equations, systems and matrices](https://kogler.wordpress.com/2008/03/21/latex-multiline-equations-systems-and-matrices/)<br>
[Equations System](https://steeven9.github.io/USI-LaTeX/html/math_equations_system.html)<br>
[Spacing](https://www.overleaf.com/learn/latex/Spacing_in_math_mode)<br>

In [1]:
import numpy as np

def сramer(A, B):
    X = np.zeros(B.size, dtype = np.float64)
    det = np.linalg.det(A)
    for i in range (B.size):
        Ai = np.array(A.T)
        Ai[i] = B
        X[i] = np.linalg.det(Ai) / det
    return X

def task_2():
    A = np.array([[0, 1, -3, 4], [1, 0, -2, 3], [3, 2, 0, -5], [4, 3, -5, 0]])
    print('A(ij)')
    print(A)
    B = np.array([-5, -4, 12, 5])
    print('B(i):')
    print(B)
    
    print('\nCramer:')
    X = сramer(A, B)
    print(X)

    print('\n1. A*X:')
    B1 = A @ X
    print(B1)
    print('Is it correst?', np.allclose(B, B1))
    
    print('\n2. Inverse matrix:')
    X2 = np.linalg.inv(A) @ B
    print(X2)
    print('Is it correst?', np.allclose(X, X2))
    
    print('\n3. numpy.linalg.solve:')
    X3 = np.linalg.solve(A, B)
    print(X3)
    print('Is it correst?', np.allclose(X, X3))
    

In [2]:
task_2()

A(ij)
[[ 0  1 -3  4]
 [ 1  0 -2  3]
 [ 3  2  0 -5]
 [ 4  3 -5  0]]
B(i):
[-5 -4 12  5]

Cramer:
[ 1.  2.  1. -1.]

1. A*X:
[-5. -4. 12.  5.]
Is it correst? True

2. Inverse matrix:
[ 1.  2.  1. -1.]
Is it correst? True

3. numpy.linalg.solve:
[ 1.  2.  1. -1.]
Is it correst? True


# Завдання 3

Обчислити значення матричного виразу:
1. З використанням універсальних функцій бібліотеки **NumPy**.
1. За допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).
1. Для обох випадків підрахувати час виконання скрипту та зробити висновок.

Порівняти всі рішення за допомогою функції **numpy.allclose()**.

$$
(A^{2} -B^{2}) \cdot (A + B) \\
\textrm{де}\quad
A = \begin{bmatrix} 7 & 2 & 0 \\ -7 & -2 & 1 \\ 1 & 1 & 0 \end{bmatrix},
B = \begin{bmatrix} 0 & 2 & 3 \\ 1 & 0 & 2 \\ 3 & 1 & 1 \end{bmatrix}
$$

In [9]:
import numpy as np

def calc_np(A, B):
    A = np.array(A)
    B = np.array(B)
    return (A@A - B@B) @ (A + B)

def add(A, B):
    size = len(A)
    C = [[0 for i in range(size)] for j in range(size)]
    for i in range(size):
        for j in range(size):
            C[i][j] = A[i][j] + B[i][j]
    return C

def sub(A, B):
    size = len(A)
    C = [[0 for i in range(size)] for j in range(size)]
    for i in range(size):
        for j in range(size):
            C[i][j] = A[i][j] - B[i][j]
    return C

def prod(A, B):
    size = len(A)
    C = [[0 for i in range(size)] for j in range(size)]
    for i in range(size):
        for j in range(size):
            for t in range(size):
                C[i][j] += A[i][t] * B[t][j]
    return C

def calc_reg(A, B):
    X1 = sub( prod(A, A), prod(B, B) )
    X2 = add(A, B)
    return prod(X1, X2)

def task_3():
    A = [ [7, 2, 0], [-7, -2, 1], [1, 1, 0] ]
    B = [ [0, 2, 3], [1, 0, 2], [3, 1, 1] ]
    
    print('=> NumPy')
    C1 = calc_np(A, B)
    print(C1)
    %timeit calc_np(A, B)
    
    print('=> Regular Python')
    C2 = calc_reg(A, B)
    print(np.array(C2))
    %timeit calc_reg(A, B)
    
    print('\nAre they identical?', np.allclose(C1, C2))


In [11]:
task_3 ()

=> NumPy
[[ 106   72   88]
 [-230 -148 -166]
 [ -30  -24  -44]]
6.06 µs ± 52.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
=> Regular Python
[[ 106   72   88]
 [-230 -148 -166]
 [ -30  -24  -44]]
30.6 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

Are they identical? True
