# Завдання 1

In [13]:
import numpy as np

def get_n(strin):
    pieces = strin.split(' ')
    if len(pieces) != 1 or not pieces[0].isnumeric():
        print('Wrong input data: it must be a number.')
        return False, 0
    n = int(pieces[0])
    return True, n

def get_n_m(strin):
    pieces = strin.split(' ')
    if len(pieces) != 2 or not pieces[0].isnumeric() or not pieces[1].isnumeric():
        print('Wrong input data: it must be two numbers.')
        return False, 0, 0
    n = int(pieces[0])
    m = int(pieces[1])
    return True, n, m

def get_array(strin):
    pieces = strin.split(' ')
    arr = []
    for p in pieces:
        if not p.isnumeric():
            print('Wrong input data: all elements must be numerical.')
            return False, []
        arr.append(int(p))
    return True, arr

### Вправа 2

Вводиться число *n*. Розставити 1 та 0 у шаховому порядку, починаючи з 1 в матриці розміром *n×n*, використовуючи слайсінг.

In [14]:
def np_2(n):
    template = np.array([0, 1] * (int(n / 2) + 1))
    line_0 = template[0:n]
    line_1 = template[1:n+1]
    return np.array([line_0, line_1] * (int(n / 2 + 0.5)))[0:n]

def reg_2(n):
    res = []
    for i in range(n):
        res.append([])
        for j in range(n):
            res[i].append(0 if not (i+j)%2 else 1)
    return res

def task_2():
    print('Enter n:')
    success, n = get_n(input())
    if not success:
        return
    
    print('=> NumPy')
    print(np_2(n))
    %timeit np_2(n)
    
    print('=> Regular Python')
    print(np.array(reg_2(n)))
    %timeit reg_2(n)

In [16]:
task_2()

Enter n:
3
=> NumPy
[[0 1 0]
 [1 0 1]
 [0 1 0]]
2.79 µs ± 47.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
=> Regular Python
[[0 1 0]
 [1 0 1]
 [0 1 0]]
1.74 µs ± 5.86 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [17]:
task_2()

Enter n:
90
=> NumPy
[[0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 ...
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]]
29.9 µs ± 242 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
=> Regular Python
[[0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 ...
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]]
813 µs ± 2.02 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Вправа 4

Вводяться числа *n* і *m*. Вивести масив розміру n×m, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до *m*–1, а всі інші елементи матриці дорівнюють 0.

In [9]:
def np_4(n, m):
    A = np.zeros((n,m), dtype=int)
    A[0] = np.arange(0, m, 1)
    return A

def reg_4(n, m):
    A = [[0 for i in range(m)] for j in range(n)]
    for j in range(0,m):
        A[0][j] = j
    return A

def task_4():
    print('Enter n and m:')
    success, n, m = get_n_m(input())
    if not success:
        return
    
    print('=> NumPy')
    print(np_4(n, m))
    %timeit np_4(n, m)
    
    print('=> Regular Python')
    print(np.array(reg_4(n, m)))
    %timeit reg_4(n, m)

In [19]:
task_4()

Enter n and m:
1 3
=> NumPy
[[0 1 2]]
1.3 µs ± 4.03 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
=> Regular Python
[[0 1 2]]
1.03 µs ± 7.56 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:
task_4()

Enter n and m:
70 90
=> NumPy
[[ 0  1  2 ... 87 88 89]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
2.34 µs ± 12.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
=> Regular Python
[[ 0  1  2 ... 87 88 89]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
151 µs ± 954 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### Вправа 5

Вводиться число *n*. Вивести масив розміру *n×n*, в якому в рядках з парними індексами стоять 1, а в інших – 0.

In [22]:
def np_5(n):
    template = np.array([1, 0] * (int(n / 2) + 1))[0:n]
    return np.repeat(template, n).reshape(n,n)

def reg_5(n):
    A = [[0 for i in range(n)] for j in range(n)]
    enen_odd = True
    for i in range(n):
        if i%2:
            continue
        for j in range(n):
            A[i][j] = 1
    return A

def task_5():
    print('Enter n:')
    success, n = get_n(input())
    if not success:
        return
    
    print('=> NumPy')
    print(np_5(n))
    %timeit np_5(n)
    
    print('=> Regular Python')
    print(np.array(reg_5(n)))
    %timeit reg_5(n)

In [23]:
task_5()

Enter n:
9
=> NumPy
[[1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]]
3.13 µs ± 29 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
=> Regular Python
[[1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]]
7.28 µs ± 67.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [24]:
task_5()

Enter n:
9
=> NumPy
[[1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]]
3.16 µs ± 32.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
=> Regular Python
[[1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]]
7.29 µs ± 32.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Вправа 8

З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульових елементів.

In [27]:
def np_8(arr):
    np_arr = np.array(arr)
    non_zero_cnt = np.count_nonzero(np_arr)
    return np_arr.size - non_zero_cnt, non_zero_cnt

def reg_8(arr):
    zero_cnt = 0
    for el in arr:
        if not el:
            zero_cnt += 1
    return zero_cnt, len(arr) - zero_cnt

def task_8():
    print('Enter array:')
    success, arr = get_array(input())
    if not success:
        return
    
    print('=> NumPy (given array)')
    print(np_8(arr))
    %timeit np_8(arr)
    print('=> Regular Python (given array)')
    print(reg_8(arr))
    %timeit reg_8(arr)
    
    arr = np.random.randint(-3, 3, 10000)
    
    print('=> NumPy (randon array with 10K elements)')
    print(np_8(arr))
    %timeit np_8(arr)
    print('=> Regular Python (randon array with 10K elements)')
    print(reg_8(arr))
    %timeit reg_8(arr)


In [29]:
task_8 ()


Enter array:
9 0 6 4 0 45
=> NumPy (given array)
(2, 4)
1.4 µs ± 2.72 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
=> Regular Python (given array)
(2, 4)
289 ns ± 3.97 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
=> NumPy (randon array with 10K elements)
(1618, 8382)
3.59 µs ± 26.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
=> Regular Python (randon array with 10K elements)
(1618, 8382)
433 µs ± 592 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Вправа 9

Вводиться число *n*. Створити масив значень від *n* до 0.

In [30]:
def np_9(n):
    return np.arange(n, -1, -1)

def reg_9(n):
    A = []
    for i in range(n+1):
        A.append(n-i)
    return A

def task_9():
    print('Enter n:')
    success, n = get_n(input())
    if not success:
        return
    
    print('=> NumPy')
    print(np_9(n))
    %timeit np_9(n)
    
    print('=> Regular')
    print(np.array(reg_9(n)))
    %timeit reg_9(n)

In [31]:
task_9()

Enter n:
10
=> NumPy
[10  9  8  7  6  5  4  3  2  1  0]
666 ns ± 2.87 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
=> Regular
[10  9  8  7  6  5  4  3  2  1  0]
869 ns ± 1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
task_9()

### Вправа 12

Створити масив одиниць розміром *n×n* та створити в ньому «рамку», що утворюється з 0.

In [32]:
def np_12(n):
    template = np.ones(n, dtype=int)
    template[0] = template[n-1] = 0
    A = np.full((n,n), template)
    A[0] = np.zeros(n, dtype=int)
    A[n-1] = np.zeros(n, dtype=int)
    return A
    

def reg_12(n):
    A = [[1 for i in range(n)] for j in range(n)]
    for i in range(n):
        A[0][i] = 0
        A[i][0] = 0
        A[n-1][i] = 0
        A[i][n-1] = 0
    return A

def task_12():
    print('Enter n:')
    success, n = get_n(input())
    if not success:
        return
    
    print('=> NumPy')
    print(np_12(n))
    %timeit np_12(n)
    
    print('=> Regular')
    print(np.array(reg_12(n)))
    %timeit reg_12(n)

In [33]:
task_12()

Enter n:
8
=> NumPy
[[0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]]
4.33 µs ± 47.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
=> Regular
[[0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]]
5.37 µs ± 60 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
task_12()

### Вправа 13

Розмістити на полі *8×8* нулі та одиниці в шахматному порядку, використовуючи функцію повторення (*).

In [34]:
def np_13(n):
    x0 = np.array([0, 1] * int(n / 2)) 
    x1 = np.array([1, 0] * int(n / 2))
    return np.array((x0, x1) * int(n / 2))
    

def reg_13(n):
    A = [[0 for i in range(n)] for j in range(n)]
    for i in range(n):
        for j in range(n):
            A[i][j] = (i+j)%2
    return A

def task_13():
    n = 8
    print('n =', n)
    
    print('=> NumPy')
    print(np_13(n))
    %timeit np_13(n)
    
    print('=> Regular')
    print(np.array(reg_13(n)))
    %timeit reg_13(n)

In [35]:
task_13()

n = 8
=> NumPy
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
4.28 µs ± 13.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
=> Regular
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
9.05 µs ± 103 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Вправа 15

Заповнити парні стовпчикі матриці розміром *n×n* одиницями, а непарні – нулями. 

In [36]:
def np_15(n):
    template = np.array([0, 1] * (int(n / 2) + 1))[0:n]
    return np.tile(template, n).reshape(n, n)

def reg_15(n):
    x = [0 for i in range(n)]
    for i in range(n):
        x[i] = i%2
    A = [x for j in range(n)]
    return A

def task_15():
    print('Enter n:')
    success, n = get_n(input())
    if not success:
        return
    
    print('=> NumPy')
    print(np_15(n))
    %timeit np_15(n)
    
    print('=> Regular')
    print(np.array(reg_15(n)))
    %timeit reg_15(n)

In [37]:
task_15()

Enter n:
9
=> NumPy
[[0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]]
5.74 µs ± 86.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
=> Regular
[[0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0]]
1.59 µs ± 20.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
task_15()

### Вправа 19

Згенерувати вектор із *n* елементів, що рівномірно розміщені на інтервалі (0,1) – тобто обидва кінці інтервалу не включені. Значення вивести до 3 знаків після коми. 


In [38]:
import random

def np_19(n):
    return np.random.random(n)

def reg_19(n):
    x = [0 for i in range(n)]
    for i in range(n):
        x[i] = random.random()
    return x

def task_19():
    print('Enter n:')
    success, n = get_n(input())
    if not success:
        return
    
    np.set_printoptions(precision=3)
    
    print('=> NumPy')
    print(np_19(n))
    %timeit np_19(n)
    
    print('=> Regular')
    print(np.array(reg_19(n)))
    %timeit reg_19(n)

In [39]:
task_19()

Enter n:
10
=> NumPy
[0.304 0.457 0.189 0.127 0.141 0.019 0.683 0.356 0.366 0.711]
792 ns ± 3.76 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
=> Regular
[0.149 0.596 0.971 0.939 0.156 0.15  0.421 0.319 0.276 0.5  ]
1.44 µs ± 16.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
task_19()